import type { SetGoBackup } from '../db/backup';

export const SETGO_V5_MIGRATION_FIXTURE_BACKUP = {
  app: 'SetGo',
  version: 1,
  exportedAt: '2026-06-29T10:00:00.000Z',
  data: {
    exercises: [
      {
        id: 'fixture_bench_press',
        nameKo: 'Bench Press',
        nameEn: 'Bench Press',
        stage: 'main',
        stageTags: ['main'],
        category: 'chest',
        categoryTags: ['chest', 'triceps'],
        description: 'Synthetic fixture exercise for migration tests.',
        defaultEmoji: 'B',
        isDefault: false,
        isActive: true,
        createdAt: '2026-06-01T00:00:00.000Z',
        updatedAt: '2026-06-01T00:00:00.000Z',
      },
      {
        id: 'fixture_lat_pulldown',
        nameKo: 'Lat Pulldown',
        nameEn: 'Lat Pulldown',
        stage: 'main',
        stageTags: ['main'],
        category: 'back',
        categoryTags: ['back', 'biceps'],
        description: 'Synthetic fixture exercise for migration tests.',
        defaultEmoji: 'L',
        isDefault: false,
        isActive: true,
        createdAt: '2026-06-01T00:00:00.000Z',
        updatedAt: '2026-06-01T00:00:00.000Z',
      },
    ],
    routines: [{
      id: 'fixture_routine',
      name: 'Fixture Upper Plan',
      splitType: 'custom',
      startDate: '2026-06-24',
      isActive: true,
      createdAt: '2026-06-01T00:00:00.000Z',
      updatedAt: '2026-06-24T00:00:00.000Z',
    }],
    routineDays: [{
      id: 'fixture_upper_day',
      routineId: 'fixture_routine',
      code: 'A',
      name: 'Upper Fixture',
      sequence: 1,
      family: 'upper',
      intensityPhase: 'hypertrophy',
    }],
    weeklySchedules: [
      {
        id: 'fixture_weekly_monday',
        routineId: 'fixture_routine',
        weekday: 1,
        routineDayId: 'fixture_upper_day',
        isRestDay: false,
      },
      {
        id: 'fixture_weekly_tuesday',
        routineId: 'fixture_routine',
        weekday: 2,
        isRestDay: true,
      },
    ],
    routineCyclePlanItems: [{
      id: 'fixture_cycle_upper',
      routineId: 'fixture_routine',
      order: 1,
      kind: 'routine',
      routineDayId: 'fixture_upper_day',
    }],
    calendarPlanOverrides: [{
      id: 'fixture_running_override',
      date: '2026-06-26',
      routineId: 'fixture_routine',
      kind: 'running',
      isRestDay: false,
      createdAt: '2026-06-24T00:00:00.000Z',
      updatedAt: '2026-06-24T00:00:00.000Z',
    }],
    routineExercisePlans: [
      {
        id: 'fixture_plan_bench',
        routineDayId: 'fixture_upper_day',
        exerciseId: 'fixture_bench_press',
        order: 1,
        plannedWeightKg: 80,
        plannedReps: 8,
        plannedSets: 3,
        plannedRir: 2,
        plannedRestSeconds: 150,
        targetRepMin: 6,
        targetRepMax: 10,
        progressionStyle: 'compound',
        preferredWeightIncrementKg: 2.5,
        note: 'Synthetic migration fixture plan.',
      },
      {
        id: 'fixture_plan_lat',
        routineDayId: 'fixture_upper_day',
        exerciseId: 'fixture_lat_pulldown',
        order: 2,
        plannedWeightKg: 55,
        plannedReps: 10,
        plannedSets: 3,
        plannedRir: 2,
        plannedRestSeconds: 120,
        targetRepMin: 8,
        targetRepMax: 12,
        progressionStyle: 'isolation',
        preferredWeightIncrementKg: 2.5,
      },
    ],
    workoutSessions: [
      {
        id: 'fixture_strength_session',
        date: '2026-06-24',
        startedAt: '2026-06-24T09:00:00.000Z',
        endedAt: '2026-06-24T10:00:00.000Z',
        timeBand: 'morning',
        routineId: 'fixture_routine',
        routineDayId: 'fixture_upper_day',
        cyclePlanItemId: 'fixture_cycle_upper',
        entryKind: 'planned',
        recommendationSnapshot: {
          kind: 'routine',
          sessionKind: 'planned',
          routineDayId: 'fixture_upper_day',
          label: 'Upper Fixture',
          source: 'cycle',
          reason: 'cycleRoutine',
          confidence: 'high',
          exerciseTargets: [
            {
              planId: 'fixture_plan_bench',
              exerciseId: 'fixture_bench_press',
              weightKg: 80,
              reps: 8,
              sets: 3,
              rir: 2,
              targetRepMin: 6,
              targetRepMax: 10,
              confidence: 'high',
              reason: 'Fixture target from planned values.',
            },
          ],
          createdAt: '2026-06-24T08:55:00.000Z',
        },
        status: 'completed',
        totalStrengthVolumeKg: 4020,
        memo: 'Synthetic fixture strength session.',
        autoSkipped: false,
        isDemo: true,
        createdAt: '2026-06-24T09:00:00.000Z',
        updatedAt: '2026-06-24T10:00:00.000Z',
      },
      {
        id: 'fixture_running_session',
        date: '2026-06-26',
        startedAt: '2026-06-26T11:00:00.000Z',
        endedAt: '2026-06-26T11:35:00.000Z',
        timeBand: 'morning',
        routineId: 'fixture_routine',
        entryKind: 'running',
        recommendationSnapshot: {
          kind: 'running',
          sessionKind: 'running',
          label: 'Fixture Run',
          source: 'override',
          reason: 'plannedRunning',
          confidence: 'high',
          createdAt: '2026-06-26T10:55:00.000Z',
        },
        status: 'completed',
        totalStrengthVolumeKg: 0,
        memo: 'Synthetic fixture running session.',
        isDemo: true,
        createdAt: '2026-06-26T11:00:00.000Z',
        updatedAt: '2026-06-26T11:35:00.000Z',
      },
    ],
    workoutExercises: [
      {
        id: 'fixture_workout_bench',
        sessionId: 'fixture_strength_session',
        exerciseId: 'fixture_bench_press',
        order: 1,
        status: 'completed',
        totalVolumeKg: 2400,
        restSeconds: 150,
        memo: 'Synthetic fixture bench work.',
      },
      {
        id: 'fixture_workout_lat',
        sessionId: 'fixture_strength_session',
        exerciseId: 'fixture_lat_pulldown',
        order: 2,
        status: 'completed',
        totalVolumeKg: 1620,
        restSeconds: 120,
      },
    ],
    workoutSets: [
      {
        id: 'fixture_set_bench_1',
        workoutExerciseId: 'fixture_workout_bench',
        setNo: 1,
        weightKg: 80,
        reps: 10,
        estimatedOneRmKg: 106.7,
        rir: 2,
        isCompleted: true,
        isWarmup: false,
        isHard: true,
        type: 'normal',
        intensityTechnique: 'straight',
      },
      {
        id: 'fixture_set_bench_2',
        workoutExerciseId: 'fixture_workout_bench',
        setNo: 2,
        weightKg: 80,
        reps: 10,
        estimatedOneRmKg: 106.7,
        rir: 1,
        isCompleted: true,
        isWarmup: false,
        isHard: true,
        type: 'normal',
        intensityTechnique: 'straight',
      },
      {
        id: 'fixture_set_lat_1',
        workoutExerciseId: 'fixture_workout_lat',
        setNo: 1,
        weightKg: 54,
        reps: 10,
        estimatedOneRmKg: 72,
        rir: 2,
        isCompleted: true,
        isWarmup: false,
        isHard: true,
        type: 'normal',
        intensityTechnique: 'straight',
      },
    ],
    cardioRecords: [{
      id: 'fixture_cardio_run',
      sessionId: 'fixture_running_session',
      order: 1,
      isDraft: false,
      source: 'imported',
      sourceName: 'Fixture Health Export',
      externalId: 'fixture-health-running-001',
      importedAt: '2026-06-26T11:40:00.000Z',
      activityType: 'running',
      environment: 'outdoor',
      location: 'Synthetic park route',
      startedAt: '2026-06-26T11:00:00.000Z',
      endedAt: '2026-06-26T11:35:00.000Z',
      durationSeconds: 2100,
      distanceKm: 5.2,
      averageSpeedKmh: 8.9,
      memo: 'Synthetic fixture cardio record.',
    }],
  },
} satisfies SetGoBackup;
